version: '3.8'

services:
    n8n:
        container_name: n8n,
        build: ,
        ports:
            - "5678:5678"
        volumes:
            - n8n-data:/home/node/.n8n
            - ./shared:/data/shared
        restart: unless-stopped

volumes:
    n8n-data:
        name: n8n-data